version: '3'

services:
  bash: &default
    build: .
    image: dannyben/rush-cli
    volumes: 
    - ./test:/test
    - ./sample-repo:/root/rush-repos/sample-repo

  test: &test
    <<: *default
    command: bats .

  ci:
    <<: *test
    volumes: []

