services:
  bash:
    build: .
    <<: &default
      image: dannyben/rush-local
      environment: 
        LC_ALL: en_US.UTF-8 # consistent sort order
      volumes: 
      - ./rush:/usr/local/bin/rush
      - ./test:/test
      - ./sample-repo:/root/rush-repos/sample-repo

  test: &test
    <<: *default
    command: bash approve

  ci:
    <<: *test
    volumes: []

