services:
  local:
    build: .
    <<: &default
      image: dannyben/rush-local
      environment: 
        LC_ALL: en_US.UTF-8 # consistent sort order
      volumes: 
      - ./rush:/usr/local/bin/rush
      - ./test:/test
      - ./sample-repo:/root/rush-repos/sample-repo

  public:
    image: dannyben/rush:latest
    build: .
    environment:
      LC_ALL: en_US.UTF-8 # consistent sort order
    entrypoint: bash
