## Script Generation

build: op generate && op man
#? Regenerate script and man pages together

generate: bashly generate --upgrade --env production "$@"
#? Regenerate script

watch: op generate --watch
#? Watch files and regenerate script on change

## Testing and Lintung

test: shellkin "$@"
#? Run tests

shellcheck: shellcheck rush setup uninstall && green "PASS shellcheck"
#? Run shellcheck tests

shfmt: shfmt -ci -i 2 -d rush setup uninstall && green "PASS shfmt"
#? Run shfmt tests

## Documentation

man: bashly render :mandoc doc && op man-zip
#? Render the man pages
#? This is called automatically when running `op generate`

private

man-zip: tar -czf ./tmp/manpages.tar.gz -C doc . && echo "saved tmp/manpages.tar.gz"
#? Create tmp/manpages.tar.gz
