name: Test
on:
  pull_request:
  push: { branches: master }

jobs:
  test:
    name: Test on ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run shellcheck tests
      run: shellcheck rush

    - name: Build container for approval tests
      run: docker-compose build

    - name: Run approval tests
      run: docker-compose run ci

