name: Test
on:
  pull_request:
  push: { branches: master }

jobs:
  test:
    name: Run test suite
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
    - name: Run shellcheck tests
      run: shellcheck rush setup
    - name: Install Shellkin
      run: curl -Ls get.dannyb.co/shellkin/setup | bash
    - name: Add repo root to PATH
      run: echo "$PWD" >> $GITHUB_PATH
    - name: Run acceptance tests
      run: shellkin

  ubuntu_setup:
    name: Setup on Ubuntu
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
    - name: Run setup
      run: |
        ./setup
        command -v rush
    - name: Run uninstall
      run: |
        ./uninstall
        ! command -v rush

  macos_setup:
    name: Setup on macOS
    runs-on: macos-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
    - name: Upgrade the outdated bash
      run: brew install bash
    - name: Run setup
      run: |
        ./setup
        command -v rush
    - name: Run uninstall
      run: |
        ./uninstall
        ! command -v rush
