name: Test
on:
  pull_request:
  push: { branches: master }

jobs:
  test:
    name: Run test suite
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run shellcheck tests
      run: shellcheck rush setup
    - name: Build container for approval tests
      run: docker compose build
    - name: Run approval tests
      run: docker compose run ci

  ubuntu_setup:
    name: Setup on Ubuntu
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run setup
      run: ./setup
    - name: Test setup artifacts
      run: test/setup_artifacts

  macos_setup:
    name: Setup on macOS
    runs-on: macos-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Upgrade the outdated bash
      run: brew install bash
    - name: Run setup
      run: ./setup
    - name: Test setup artifacts
      run: test/setup_artifacts

  static_analysis:
    name: Static analysis

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # Rush needed for easy installation of latest shfmt
    - name: Install rush
      run: curl -Ls http://get.dannyb.co/rush/setup | bash

    - name: Connect rush repo
      run: rush clone dannyben --shallow --default

    - name: Install shfmt
      run: rush get shfmt

    # libyaml needed for Ruby's YAML library
    - name: Install OS dependencies
      run: sudo apt-get -y install libyaml-dev

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with: 
        ruby-version: '3.1'
        bundler-cache: true

    - name: Run shellcheck tests
      run: shellcheck rush

    - name: Run shfmt tests
      run: shfmt -d -i 2 -ci rush
